title:            Super-Serious
description:      The only serious web on the web
url:              http://super-serious.com/
signoff:          Ernest
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-89939985-1

links:
  - name:         Blog
    url:          /
  - name:         About
    url:          /about
  #   external:     true
  # - name:         GitHub
  #   url:          http://github.com/muan
  #   external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
