# Site settings
title: A Beautiful Font
email: ewalzel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is so beautiful it makes you cry.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ErnestWalzel
github_username:  eronisko

# Build settings
markdown: kramdown

# Plugins
gems: [jekyll-haml]
